### ISSUE TITLE
dependent ubuntu binary package "glibc" mentioned in setup.txt does not exist in Ubuntu

### ISSUE THREAD

**Issue by kcleung** [mattmcd/NaCl#2]
I am trying to set up my Ubuntu 15.10, and tried to install all dependent packages mentioned in setup.txt.  However, there are no packages called "glibc".  Could you please update the list?

**Comment by mattmcd** [comment]
Thanks for trying it out.  I created the setup.txt from my command history on a test EC2 node so it's probable the glibc line is an error and the package immediately following is the correct one.  I'll remove the glibc line from setup.txt.

**Comment by mattmcd** [comment]
Removed in d152e400030c89d1c6ca6d8217a67cdfadc91e8b
