### ISSUE TITLE
NaCl Ports renamed  webports, need to update setup.txt

### ISSUE THREAD

**Issue by kcleung** [mattmcd/NaCl#4]
Google has recently renamed naclports to webports, so would you please replace the instruction in setup.txt:
gclient config --name-src https://chromium/googlesource.com/external/naclports.git

with:
gclient config --name-src https://chromium/googlesource.com/webports

Also, these packages are not installed by ubuntu by default, so we also need to add them to the dependency list:
curl python-dev python-pip

**Comment by mattmcd** [comment]
Made the naclports -> webports change.  Added curl to list of packages to install.
For Python, just added comment saying to install python as people have different preferences on how to do this e.g. Anacaonda versus apt-get.
